### PR TITLE
Fix regression and styling on session page

### PR DESCRIPTION
**Pull request by jverswijver**
include in your PR:
fix vathes#70 
fix vathes#71
fix vathes#72 
fix vathes#73
fix vathes#74

### CODE REVIEW

**Review by guzman-raphael — CHANGES_REQUESTED** [review]
@jverswijver :muscle: Nice work man! Thank you! :muscle:

Would you update the description here to properly link the issues? Namely just use this syntax for each issue patched:

 ```
Fix organization/repository#number
```

There are a few small items that would be good to include but to make it more straightforward, I've issued a [PR](https://github.com/jverswijver/ibl-navigator/pull/1) to you with the specifics about them. Once we merge that, we should be good to approve/merge here.

Also, found one more regression issue but it is only related to styling/formatting. Since there is no data loss, we can treat it with lower priority but would be nice to have a look when you get a chance. I've filed it in a separate [issue](https://github.com/vathes/ibl-navigator/issues/77) to track it so we can proceed here as discussed above.

**Review by guzman-raphael — APPROVED** [review]
@jverswijver Awesome :sunglasses:

**Comment by guzman-raphael** [comment]
@zitrosolrac This PR now looks ready to merge. Since it is your fork, would you merge it in so that it updates your open [PR](https://github.com/vathes/ibl-navigator/pull/69)?

**Comment by jverswijver** [comment]
It seems to link to issues in the main repo all you have to do is `organization#issuenumber`.

I have gone ahead and merged the changes you pr'd @guzman-raphael. I have also looked at the issue you linked, since its lower priority it might be worth it to just wait a few days in case you make some progress with optimizing the docker deployment. Waiting 5+ minutes every time I docker-compose up the project really wastes dev time.

**Comment by guzman-raphael** [comment]
@jverswijver Yes, that is a great point and I agree. Filed a new [issue](https://github.com/vathes/ibl-navigator/issues/78) to track the build optimization and treating it as a 'sort-of' regression. We can treat that as a blocker or dependency before working on table formatting [issue](https://github.com/vathes/ibl-navigator/issues/77). For now, I don't quite have the bandwidth to patch that now so let's defer.

**Pull request merged**
